version: '3'
services:
  msql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "kiii2023"
        MSSQL_PID: Express
    ports:
        - "1433:1433"
  studyflow-app:
    build: .
    ports:
        - "8080:80"