apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-studyflow
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "studyflow-kiii.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studyflow-backend
                port:
                  number: 80